# This is a basic workflow to help you get started with Actions

name: CI

on:
  #pull_request_review:
  #  types: [submitted]
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      #- name: Add Labels
      #  uses: christianvuerings/add-labels@v1.1
      #  with:
      #    labels: major
      #  env:
      #    GITHUB_TOKEN: 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

      - name: label_sponsor
        uses: JasonEtco/is-sponsor-label-action@v1
        with:
          label: Sponsor ❤️
        env:
          GITHUB_TOKEN: $
